FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SYSUAPP

Polls is a simple API allowing consumers to view polls and vote in them.

## UserCollections [/user]

### Login [POST]

+ Request (application/json)

        {
            "netId":fangjm5,
            "pass":"15331074"
        
        }
+ Response 200 (application/json)

        {
            "succcess":true,
            "userId":"sdcs1074"
        }

## UserInfoCollections [/users/{id}]
This operation is to get user info by user's id
+ Parameters
    - id : "1533" (string, required)

### GetUserInfo [GET]

+ Request (application/json)

        {
            "id":15331074
        }
+ Response 200 (application/json)

        {
            "id":15331074,
            "info":{
                "name":"sysuygm",
                "avatar":"aveatar's url",
                "college":12,
                "major":4,
                "grade":3,
                "mobile":"13789897867",
                "sex":1,
                "nation":1
            }
        }
        
## CourseInfoCollection [courses/select/]


### GetCoursesForSelect [GET]

+ Request (application/json)

        {
            "college":14,
            "grade":3,
            "major":3
        }
+ Response (apllication/json)

        {
            "id":"15331000",
            "college":14,
            "grade":3,
            "major":3,
            "courses":{
                "common":[
                    {
                        "coursename":"并行程序设计",
                        "courseid":"sdcs1234",
                        "credit":3,
                        "capacity":120
                    }
                ]
            }
        }