FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# SYSUAPP

Polls is a simple API allowing consumers to view polls and vote in them.

## UserCollections [/users]

### Login [POST]

+ Request (application/json)

        {
            "id":15331074,
            "pass":"15331074"
        
        }
+ Response 200 (application/json)

        {
            "succcess":true
        }

## UserInfoCollections [/user/{?id}]

+ Parameters
    - key : "1533" (string, required)
    
### GetUserInfo [GET]

+ Request (application/json)

        {
            "id":15331074
        }
+ Response 200 (application/json)

        {
            "id":15331074,
            "info":{
                "name":"sysuygm",
                "avatar":"aveatar's url",
                "college":12,
                "major":4,
                "grade":3,
                "mobile":"13789897867",
                "sex":1,
                "nation":1
            }
        }